In [14]:
import pandas as pd

df1 = pd.DataFrame({
    'ID' : [1,2,3],
    'Name' : ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID' : [4,5],
    'Name' : ['David', 'Emma']
})

df = pd.concat([df1, df2], axis=1, ignore_index = True)
df

   0        1    2      3
0  1    Alice  4.0  David
1  2      Bob  5.0   Emma
2  3  Charlie  NaN    NaN

In [9]:
df.isnull()

       0      1      2      3
0  False  False  False  False
1  False  False  False  False
2  False  False   True   True

In [10]:
df.isnull().sum()

0    0
1    0
2    1
3    1
dtype: int64

In [13]:
df = df.dropna() # elimina righe con NaN
df

   0      1    2      3
0  1  Alice  4.0  David
1  2    Bob  5.0   Emma

In [20]:
print(df)
df[2].fillna(df[2].mean())

   0        1    2      3
0  1    Alice  4.0  David
1  2      Bob  5.0   Emma
2  3  Charlie  NaN    NaN

0    4.0
1    5.0
2    4.5
Name: 2, dtype: float64

In [45]:
from faker import Faker 
import numpy as np 

np.random.seed(42)
Faker.seed(42)
fake = Faker()

n = 5

df_part1 = pd.DataFrame({
    'ID' : np.arange(n), 
    'Name' : [fake.first_name() for _ in range(n)],
    'Score' : np.random.randint(1, 101, n)
})

df_part2 = pd.DataFrame({
    'ID' : np.arange(n, 2*n), 
    'Name' : [fake.first_name() for _ in range(n)],
    'Score' : np.random.randint(1, 101, n)
})

df = pd.concat([df_part1, df_part2], ignore_index=True)
# df['ID'] = np.arange(len(df))
df

   ID         Name  Score
0   0     Danielle     52
1   1        Angel     93
2   2       Joshua     15
3   3      Jeffrey     72
4   4         Jill     61
5   5        Erica     21
6   6     Patricia     83
7   7  Christopher     87
8   8       Robert     75
9   9      Anthony     75

In [ ]:
# or we could use uuid for the IDs generation for df_part1, df_part2
import uuid

df_part1['ID'] = [str(uuid.uuid4()) for _ in range(n)]
df_part1

                                     ID      Name  Score
0  23a35920-9d01-421b-8846-4ba33ed14eaf  Danielle     52
1  a4130a19-01d1-494e-b823-5c4d318b533b     Angel     93
2  3d4167a0-db17-4da3-815b-a74efa6ba0e0    Joshua     15
3  1192be1f-31c5-4b16-8a93-b2a6e592d1c2   Jeffrey     72
4  59195f65-b763-452e-b397-1fc2b8fc54ed      Jill     61

In [42]:
random = np.random.randint(0,10,3)
print(random)
df.loc[random, 'Score'] = np.nan
df

[7 4 3]

   ID         Name  Score
0   0     Danielle   52.0
1   1        Angel   93.0
2   2       Joshua   15.0
3   3      Jeffrey    NaN
4   4         Jill    NaN
5   0        Erica   21.0
6   1     Patricia   83.0
7   2  Christopher    NaN
8   3       Robert   75.0
9   4      Anthony   75.0

In [43]:
df.isnull().sum()
df['Score'] = df['Score'].fillna(df['Score'].mean())
df

   ID         Name      Score
0   0     Danielle  52.000000
1   1        Angel  93.000000
2   2       Joshua  15.000000
3   3      Jeffrey  59.142857
4   4         Jill  59.142857
5   0        Erica  21.000000
6   1     Patricia  83.000000
7   2  Christopher  59.142857
8   3       Robert  75.000000
9   4      Anthony  75.000000