In [3]:
import pandas as pd
import numpy as np 
from faker import Faker 

np.random.seed(42)

df1 = pd.DataFrame({
    'ID' : [1,2,3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [1,2,4],
    'Score': [80, 90, 70]
})

merged = pd.merge(df1, df2, on='ID', how='outer')
print(merged)

   ID     Name  Score
0   1    Alice   80.0
1   2      Bob   90.0
2   3  Charlie    NaN
3   4      NaN   70.0

In [5]:
pd.merge(df1, df2, left_index=True, right_index=True)

   ID_x     Name  ID_y  Score
0     1    Alice     1     80
1     2      Bob     2     90
2     3  Charlie     4     70

In [9]:
fake = Faker()
n=10

cities = ['Roma', 'Milano', 'Bari', 'Firenze', 'Napoli', 'Pisa']

df_customers = pd.DataFrame({
    'CustomerID' : np.random.randint(0,10,n),
    'Name' : [f"{fake.first_name()} {fake.last_name()}" for _ in range(n)],
    'City' : np.random.choice(cities, n)
})

df_orders = pd.DataFrame({
    'OrderID' : np.arange(n),
    'CustomerID' : np.random.randint(0,10,n),
    'OrderAmount': np.random.randint(0,200,n)
})

print(pd.merge(df_customers, df_orders, on='CustomerID'))
print(pd.merge(df_customers, df_orders, how='left'))
print(pd.merge(df_customers, df_orders, how='outer'))

    CustomerID              Name     City  OrderID  OrderAmount
0            0     Nicholas Cook     Bari        2          100
1            6       Lisa Taylor     Roma        3          174
2            6       Lisa Taylor     Roma        4          130
3            7     Carlos Tanner   Napoli        0           34
4            7     Carlos Tanner   Napoli        5            0
5            7     Carlos Tanner   Napoli        8          102
6            0       Maria Klein   Milano        2          100
7            7       Brandy Yang   Milano        0           34
8            7       Brandy Yang   Milano        5            0
9            7       Brandy Yang   Milano        8          102
10           7  Jennifer Gilbert     Roma        0           34
11           7  Jennifer Gilbert     Roma        5            0
12           7  Jennifer Gilbert     Roma        8          102
13           2         Sarah Ray  Firenze        7          141
14           0      Jason Henson     Roma        2          100
    CustomerID              Name     City  OrderID  OrderAmount
0            0     Nicholas Cook     Bari      2.0        100.0
1            8    Debra Alvarado     Bari      NaN          NaN
2            6       Lisa Taylor     Roma      3.0        174.0
3            6       Lisa Taylor     Roma      4.0        130.0
4            8  William Gonzales     Bari      NaN          NaN
5            7     Carlos Tanner   Napoli      0.0         34.0
6            7     Carlos Tanner   Napoli      5.0          0.0
7            7     Carlos Tanner   Napoli      8.0        102.0
8            0       Maria Klein   Milano      2.0        100.0
9            7       Brandy Yang   Milano      0.0         34.0
10           7       Brandy Yang   Milano      5.0          0.0
11           7       Brandy Yang   Milano      8.0        102.0
12           7  Jennifer Gilbert     Roma      0.0         34.0
13           7  Jennifer Gilbert     Roma      5.0          0.0
14           7  Jennifer Gilbert     Roma      8.0        102.0
15           2         Sarah Ray  Firenze      7.0        141.0
16           0      Jason Henson     Roma      2.0        100.0
    CustomerID              Name     City  OrderID  OrderAmount
0            0     Nicholas Cook     Bari      2.0        100.0
1            0       Maria Klein   Milano      2.0        100.0
2            0      Jason Henson     Roma      2.0        100.0
3            1               NaN      NaN      1.0        192.0
4            2         Sarah Ray  Firenze      7.0        141.0
5            4               NaN      NaN      6.0          4.0
6            5               NaN      NaN      9.0         26.0
7            6       Lisa Taylor     Roma      3.0        174.0
8            6       Lisa Taylor     Roma      4.0        130.0
9            7     Carlos Tanner   Napoli      0.0         34.0
10           7     Carlos Tanner   Napoli      5.0          0.0
11           7     Carlos Tanner   Napoli      8.0        102.0
12           7       Brandy Yang   Milano      0.0         34.0
13           7       Brandy Yang   Milano      5.0          0.0
14           7       Brandy Yang   Milano      8.0        102.0
15           7  Jennifer Gilbert     Roma      0.0         34.0
16           7  Jennifer Gilbert     Roma      5.0          0.0
17           7  Jennifer Gilbert     Roma      8.0        102.0
18           8    Debra Alvarado     Bari      NaN          NaN
19           8  William Gonzales     Bari      NaN          NaN

    CustomerID             Name     City  OrderID  OrderAmount
0            1  Victoria Adkins     Pisa      2.0         81.0
1            1  Victoria Adkins     Pisa      4.0         52.0
2            9     Angela Perez     Roma      3.0        110.0
3            9     Angela Perez     Roma      5.0         23.0
4            8     Andrew Reyes  Firenze      9.0         40.0
5            9       Eric Green   Milano      3.0        110.0
6            9       Eric Green   Milano      5.0         23.0
7            4      Randy Kelly  Firenze      NaN          NaN
8            1      Brian Silva   Milano      2.0         81.0
9            1      Brian Silva   Milano      4.0         52.0
10           3  Kathleen Powell     Pisa      0.0        189.0
11           3  Kathleen Powell     Pisa      6.0        153.0
12           6   Albert Bernard     Pisa      8.0        123.0
13           7  Heather Cochran     Pisa      7.0        187.0
14           2      Alan Bolton   Milano      NaN          NaN