In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
df = pd.read_csv(url, sep='\t')

In [3]:
df.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

What is the number of observations in the dataset?

In [6]:
df.shape[0]

4622

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

What is the number of columns in the dataset?

In [8]:
df.shape[1]

5

Print the name of all the columns.

In [13]:
print("Features: ")
for col in df.columns :
    print(f"* {col} ({df[col].dtype})")

Features:
* order_id (int64)
* quantity (int64)
* item_name (object)
* choice_description (object)
* item_price (object)

In [14]:
for col, dtype in df.dtypes.items():
    print(f"* {col} ({dtype})")

* order_id (int64)
* quantity (int64)
* item_name (object)
* choice_description (object)
* item_price (object)

How is the dataset indexed?

In [18]:
df.index

RangeIndex(start=0, stop=4622, step=1)

Which was the most-ordered item?

In [30]:
items = df.groupby('item_name')
quantities = items['quantity'].sum().sort_values(ascending = False)
print(f"quantities per item (top 10): \n{quantities.head(10)}")

print(f"\nmost-ordered item: {quantities.head(1)}\n")

quantities per item (top 10):
item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

most-ordered item: item_name
Chicken Bowl    761
Name: quantity, dtype: int64

For the most-ordered item, how many items were ordered?

In [40]:
mostordered_item = quantities.index[0]
print(mostordered_item)

howmany_times = quantities.iloc[0]
print(howmany_times)

Chicken Bowl
761

What was the most ordered item in the choice_description column?

In [42]:
for col, dtype in df.dtypes.items():
    print(col)

order_id
quantity
item_name
choice_description
item_price

In [48]:
descr = df.groupby('choice_description')
pd.DataFrame(descr['quantity'].sum().sort_values(ascending=False)).head(1)

                    quantity
choice_description
[Diet Coke]              159

How many items were orderd in total?

In [57]:
total_items_orders = df['quantity'].sum()
print(f"{total_items_orders} <-- total items ordered (sum of quantity)\n{df.shape[0]} <-- number of rows")

4972 <-- total items ordered (sum of quantity)
4622 <-- number of rows

In [60]:
print(df.dtypes)
df.head(1)

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39

Turn the item price into a float

In [62]:
dollarizer = lambda x : float(x[1:-1])
df['item_price'] = df['item_price'].apply(dollarizer)

In [63]:
df.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [69]:
df.item_price.dtype

dtype('float64')

How much was the revenue for the period in the dataset?

In [72]:
revenue = (df['quantity']*df['item_price']).sum()
print(f"Revenue was: $ {np.round(revenue,2)}")

Revenue was: $ 39237.02

How many orders were made in the period?

In [73]:
for col in df.columns :
    print(col)

order_id
quantity
item_name
choice_description
item_price

In [75]:
orders = df.order_id.value_counts().count()
orders

np.int64(1834)

In [80]:
df['order_id'].nunique()

1834

Series.value_counts() counts the number of times each unique value appears in a pandas Series.

It returns a new Series where:

The index = unique values

The values = their counts

In [ ]:
print(f"df.order_id.unique() = {df.order_id.unique()}")
print(f"df.order_id.nunique() = {df.order_id.nunique()}")
print(f"df['order_id'].value_counts().count() = {df.order_id.value_counts().count()}")

df.order_id.unique() = [   1    2    3 ... 1832 1833 1834]
df.order_id.nunique() = 1834
df['order_id'].value_counts() = 1834

What is the average revenue amount per order?

In [87]:
for col in df.columns : 
    print(col)

order_id
quantity
item_name
choice_description
item_price

In [91]:
tot_revenue = (df.quantity*df.item_price).sum()
tot_orders = df.order_id.nunique() 
print(f"tot_revenue / tot_orders = {tot_revenue/tot_orders:.2f}")

tot_revenue / tot_orders = 21.39

In [93]:
df['revenue'] = df['quantity'] * df['item_price'] 
order_grouped = df.groupby('order_id')['revenue'].sum()
order_grouped.mean()

np.float64(21.39423118865867)

In [94]:
df.groupby('order_id')['revenue'].sum().mean()

np.float64(21.39423118865867)

How many different items are sold?

In [96]:
df.item_name.nunique()

50

In [97]:
df.item_name.value_counts().count()

np.int64(50)